// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/chat/data/collections/cached_conversation.dart';
import 'features/chat/data/collections/cached_message.dart';
import 'features/chat/data/collections/cached_profile.dart';
import 'features/chat/data/collections/failed_message.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 4851997573193905597),
    name: 'CachedConversation',
    lastPropertyId: const obx_int.IdUid(15, 5102176737288601867),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 3669701475855231047),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4017578857605168392),
        name: 'id',
        type: 9,
        flags: 34848,
        indexId: const obx_int.IdUid(1, 6495383002296480796),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4834733327882252851),
        name: 'participant1',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5701255342268181453),
        name: 'participant2',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 7810566601837534930),
        name: 'lastMessage',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4296713032189035442),
        name: 'lastMessageAt',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2866343786920375314),
        name: 'lastMessageSenderId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 372122981990526341),
        name: 'p1UnreadCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 160852951170182369),
        name: 'p2UnreadCount',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 7029959336161744500),
        name: 'p1IsPinned',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 6927858441468763293),
        name: 'p2IsPinned',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 4467205447676080237),
        name: 'p1IsHidden',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 5066584943858499344),
        name: 'p2IsHidden',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 3923516043781743625),
        name: 'createdAt',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 5102176737288601867),
        name: 'syncedAt',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 282038241542904864),
    name: 'CachedMessage',
    lastPropertyId: const obx_int.IdUid(15, 4765953919967120532),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6813045598038905797),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6317229170165966520),
        name: 'id',
        type: 9,
        flags: 34848,
        indexId: const obx_int.IdUid(2, 9206269488399774217),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1107407830626290404),
        name: 'conversationId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(3, 2906754777075579957),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 4698167802815312157),
        name: 'senderId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2447177151411105811),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 5482535668441099760),
        name: 'mediaUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2730663715513408509),
        name: 'messageType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1046580246195602035),
        name: 'isSeen',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 7137472342229755726),
        name: 'replyToMessageId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 5861492724513333542),
        name: 'callId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 1939757523512495420),
        name: 'createdAt',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 5913786029462932662),
        name: 'syncedAt',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(13, 5728235052021884871),
        name: 'replyContent',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(14, 5987428442201698018),
        name: 'replySenderId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(15, 4765953919967120532),
        name: 'replyMessageType',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 8110163023968195589),
    name: 'CachedProfile',
    lastPropertyId: const obx_int.IdUid(8, 5659051066362104544),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 5191751081817482222),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 6527039223559366200),
        name: 'id',
        type: 9,
        flags: 34848,
        indexId: const obx_int.IdUid(4, 5268681985073639027),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2947113064333731585),
        name: 'username',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3386681732164686963),
        name: 'fullName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6464953493547624091),
        name: 'avatarUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 1658833405502254868),
        name: 'coverUrl',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2154629517283724291),
        name: 'createdAt',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 5659051066362104544),
        name: 'syncedAt',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(4, 5440757973749173711),
    name: 'FailedMessage',
    lastPropertyId: const obx_int.IdUid(11, 7662968625500453152),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1996280803002302477),
        name: 'obxId',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5150548208129361110),
        name: 'localId',
        type: 9,
        flags: 34848,
        indexId: const obx_int.IdUid(5, 6300843504326688344),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2643110951707863221),
        name: 'conversationId',
        type: 9,
        flags: 2048,
        indexId: const obx_int.IdUid(6, 3675575870221635885),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2387426220608467089),
        name: 'senderId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 6887154596921878520),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 7597006086005911025),
        name: 'messageType',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2146121660703816268),
        name: 'replyToMessageId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 2358009651766649374),
        name: 'createdAt',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 6953153228300209467),
        name: 'replyContent',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 2863149560943775435),
        name: 'replySenderId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 7662968625500453152),
        name: 'mediaUrl',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(4, 5440757973749173711),
    lastIndexId: const obx_int.IdUid(6, 3675575870221635885),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    CachedConversation: obx_int.EntityDefinition<CachedConversation>(
      model: _entities[0],
      toOneRelations: (CachedConversation object) => [],
      toManyRelations: (CachedConversation object) => {},
      getId: (CachedConversation object) => object.obxId,
      setId: (CachedConversation object, int id) {
        object.obxId = id;
      },
      objectToFB: (CachedConversation object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final participant1Offset = fbb.writeString(object.participant1);
        final participant2Offset = fbb.writeString(object.participant2);
        final lastMessageOffset = object.lastMessage == null
            ? null
            : fbb.writeString(object.lastMessage!);
        final lastMessageAtOffset = object.lastMessageAt == null
            ? null
            : fbb.writeString(object.lastMessageAt!);
        final lastMessageSenderIdOffset = object.lastMessageSenderId == null
            ? null
            : fbb.writeString(object.lastMessageSenderId!);
        final createdAtOffset = fbb.writeString(object.createdAt);
        final syncedAtOffset = fbb.writeString(object.syncedAt);
        fbb.startTable(16);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, participant1Offset);
        fbb.addOffset(3, participant2Offset);
        fbb.addOffset(4, lastMessageOffset);
        fbb.addOffset(5, lastMessageAtOffset);
        fbb.addOffset(6, lastMessageSenderIdOffset);
        fbb.addInt64(7, object.p1UnreadCount);
        fbb.addInt64(8, object.p2UnreadCount);
        fbb.addBool(9, object.p1IsPinned);
        fbb.addBool(10, object.p2IsPinned);
        fbb.addBool(11, object.p1IsHidden);
        fbb.addBool(12, object.p2IsHidden);
        fbb.addOffset(13, createdAtOffset);
        fbb.addOffset(14, syncedAtOffset);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = CachedConversation()
          ..obxId = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..id = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..participant1 = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..participant2 = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..lastMessage = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 12)
          ..lastMessageAt = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 14)
          ..lastMessageSenderId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 16)
          ..p1UnreadCount = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            18,
            0,
          )
          ..p2UnreadCount = const fb.Int64Reader().vTableGet(
            buffer,
            rootOffset,
            20,
            0,
          )
          ..p1IsPinned = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            22,
            false,
          )
          ..p2IsPinned = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            24,
            false,
          )
          ..p1IsHidden = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            26,
            false,
          )
          ..p2IsHidden = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            28,
            false,
          )
          ..createdAt = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 30, '')
          ..syncedAt = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 32, '');

        return object;
      },
    ),
    CachedMessage: obx_int.EntityDefinition<CachedMessage>(
      model: _entities[1],
      toOneRelations: (CachedMessage object) => [],
      toManyRelations: (CachedMessage object) => {},
      getId: (CachedMessage object) => object.obxId,
      setId: (CachedMessage object, int id) {
        object.obxId = id;
      },
      objectToFB: (CachedMessage object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final conversationIdOffset = fbb.writeString(object.conversationId);
        final senderIdOffset = fbb.writeString(object.senderId);
        final contentOffset = object.content == null
            ? null
            : fbb.writeString(object.content!);
        final mediaUrlOffset = object.mediaUrl == null
            ? null
            : fbb.writeString(object.mediaUrl!);
        final messageTypeOffset = fbb.writeString(object.messageType);
        final replyToMessageIdOffset = object.replyToMessageId == null
            ? null
            : fbb.writeString(object.replyToMessageId!);
        final callIdOffset = object.callId == null
            ? null
            : fbb.writeString(object.callId!);
        final createdAtOffset = fbb.writeString(object.createdAt);
        final syncedAtOffset = fbb.writeString(object.syncedAt);
        final replyContentOffset = object.replyContent == null
            ? null
            : fbb.writeString(object.replyContent!);
        final replySenderIdOffset = object.replySenderId == null
            ? null
            : fbb.writeString(object.replySenderId!);
        final replyMessageTypeOffset = object.replyMessageType == null
            ? null
            : fbb.writeString(object.replyMessageType!);
        fbb.startTable(16);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, conversationIdOffset);
        fbb.addOffset(3, senderIdOffset);
        fbb.addOffset(4, contentOffset);
        fbb.addOffset(5, mediaUrlOffset);
        fbb.addOffset(6, messageTypeOffset);
        fbb.addBool(7, object.isSeen);
        fbb.addOffset(8, replyToMessageIdOffset);
        fbb.addOffset(9, callIdOffset);
        fbb.addOffset(10, createdAtOffset);
        fbb.addOffset(11, syncedAtOffset);
        fbb.addOffset(12, replyContentOffset);
        fbb.addOffset(13, replySenderIdOffset);
        fbb.addOffset(14, replyMessageTypeOffset);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = CachedMessage()
          ..obxId = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..id = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..conversationId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..senderId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..content = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 12)
          ..mediaUrl = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 14)
          ..messageType = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 16, '')
          ..isSeen = const fb.BoolReader().vTableGet(
            buffer,
            rootOffset,
            18,
            false,
          )
          ..replyToMessageId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 20)
          ..callId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 22)
          ..createdAt = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 24, '')
          ..syncedAt = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 26, '')
          ..replyContent = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 28)
          ..replySenderId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 30)
          ..replyMessageType = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 32);

        return object;
      },
    ),
    CachedProfile: obx_int.EntityDefinition<CachedProfile>(
      model: _entities[2],
      toOneRelations: (CachedProfile object) => [],
      toManyRelations: (CachedProfile object) => {},
      getId: (CachedProfile object) => object.obxId,
      setId: (CachedProfile object, int id) {
        object.obxId = id;
      },
      objectToFB: (CachedProfile object, fb.Builder fbb) {
        final idOffset = fbb.writeString(object.id);
        final usernameOffset = fbb.writeString(object.username);
        final fullNameOffset = object.fullName == null
            ? null
            : fbb.writeString(object.fullName!);
        final avatarUrlOffset = object.avatarUrl == null
            ? null
            : fbb.writeString(object.avatarUrl!);
        final coverUrlOffset = object.coverUrl == null
            ? null
            : fbb.writeString(object.coverUrl!);
        final createdAtOffset = fbb.writeString(object.createdAt);
        final syncedAtOffset = fbb.writeString(object.syncedAt);
        fbb.startTable(9);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, idOffset);
        fbb.addOffset(2, usernameOffset);
        fbb.addOffset(3, fullNameOffset);
        fbb.addOffset(4, avatarUrlOffset);
        fbb.addOffset(5, coverUrlOffset);
        fbb.addOffset(6, createdAtOffset);
        fbb.addOffset(7, syncedAtOffset);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = CachedProfile()
          ..obxId = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..id = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..username = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..fullName = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 10)
          ..avatarUrl = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 12)
          ..coverUrl = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 14)
          ..createdAt = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 16, '')
          ..syncedAt = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 18, '');

        return object;
      },
    ),
    FailedMessage: obx_int.EntityDefinition<FailedMessage>(
      model: _entities[3],
      toOneRelations: (FailedMessage object) => [],
      toManyRelations: (FailedMessage object) => {},
      getId: (FailedMessage object) => object.obxId,
      setId: (FailedMessage object, int id) {
        object.obxId = id;
      },
      objectToFB: (FailedMessage object, fb.Builder fbb) {
        final localIdOffset = fbb.writeString(object.localId);
        final conversationIdOffset = fbb.writeString(object.conversationId);
        final senderIdOffset = fbb.writeString(object.senderId);
        final contentOffset = object.content == null
            ? null
            : fbb.writeString(object.content!);
        final messageTypeOffset = fbb.writeString(object.messageType);
        final replyToMessageIdOffset = object.replyToMessageId == null
            ? null
            : fbb.writeString(object.replyToMessageId!);
        final createdAtOffset = fbb.writeString(object.createdAt);
        final replyContentOffset = object.replyContent == null
            ? null
            : fbb.writeString(object.replyContent!);
        final replySenderIdOffset = object.replySenderId == null
            ? null
            : fbb.writeString(object.replySenderId!);
        final mediaUrlOffset = object.mediaUrl == null
            ? null
            : fbb.writeString(object.mediaUrl!);
        fbb.startTable(12);
        fbb.addInt64(0, object.obxId);
        fbb.addOffset(1, localIdOffset);
        fbb.addOffset(2, conversationIdOffset);
        fbb.addOffset(3, senderIdOffset);
        fbb.addOffset(4, contentOffset);
        fbb.addOffset(5, messageTypeOffset);
        fbb.addOffset(6, replyToMessageIdOffset);
        fbb.addOffset(7, createdAtOffset);
        fbb.addOffset(8, replyContentOffset);
        fbb.addOffset(9, replySenderIdOffset);
        fbb.addOffset(10, mediaUrlOffset);
        fbb.finish(fbb.endTable());
        return object.obxId;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);

        final object = FailedMessage()
          ..obxId = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
          ..localId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 6, '')
          ..conversationId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 8, '')
          ..senderId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 10, '')
          ..content = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 12)
          ..messageType = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 14, '')
          ..replyToMessageId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 16)
          ..createdAt = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGet(buffer, rootOffset, 18, '')
          ..replyContent = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 20)
          ..replySenderId = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 22)
          ..mediaUrl = const fb.StringReader(
            asciiOptimization: true,
          ).vTableGetNullable(buffer, rootOffset, 24);

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [CachedConversation] entity fields to define ObjectBox queries.
class CachedConversation_ {
  /// See [CachedConversation.obxId].
  static final obxId = obx.QueryIntegerProperty<CachedConversation>(
    _entities[0].properties[0],
  );

  /// See [CachedConversation.id].
  static final id = obx.QueryStringProperty<CachedConversation>(
    _entities[0].properties[1],
  );

  /// See [CachedConversation.participant1].
  static final participant1 = obx.QueryStringProperty<CachedConversation>(
    _entities[0].properties[2],
  );

  /// See [CachedConversation.participant2].
  static final participant2 = obx.QueryStringProperty<CachedConversation>(
    _entities[0].properties[3],
  );

  /// See [CachedConversation.lastMessage].
  static final lastMessage = obx.QueryStringProperty<CachedConversation>(
    _entities[0].properties[4],
  );

  /// See [CachedConversation.lastMessageAt].
  static final lastMessageAt = obx.QueryStringProperty<CachedConversation>(
    _entities[0].properties[5],
  );

  /// See [CachedConversation.lastMessageSenderId].
  static final lastMessageSenderId =
      obx.QueryStringProperty<CachedConversation>(_entities[0].properties[6]);

  /// See [CachedConversation.p1UnreadCount].
  static final p1UnreadCount = obx.QueryIntegerProperty<CachedConversation>(
    _entities[0].properties[7],
  );

  /// See [CachedConversation.p2UnreadCount].
  static final p2UnreadCount = obx.QueryIntegerProperty<CachedConversation>(
    _entities[0].properties[8],
  );

  /// See [CachedConversation.p1IsPinned].
  static final p1IsPinned = obx.QueryBooleanProperty<CachedConversation>(
    _entities[0].properties[9],
  );

  /// See [CachedConversation.p2IsPinned].
  static final p2IsPinned = obx.QueryBooleanProperty<CachedConversation>(
    _entities[0].properties[10],
  );

  /// See [CachedConversation.p1IsHidden].
  static final p1IsHidden = obx.QueryBooleanProperty<CachedConversation>(
    _entities[0].properties[11],
  );

  /// See [CachedConversation.p2IsHidden].
  static final p2IsHidden = obx.QueryBooleanProperty<CachedConversation>(
    _entities[0].properties[12],
  );

  /// See [CachedConversation.createdAt].
  static final createdAt = obx.QueryStringProperty<CachedConversation>(
    _entities[0].properties[13],
  );

  /// See [CachedConversation.syncedAt].
  static final syncedAt = obx.QueryStringProperty<CachedConversation>(
    _entities[0].properties[14],
  );
}

/// [CachedMessage] entity fields to define ObjectBox queries.
class CachedMessage_ {
  /// See [CachedMessage.obxId].
  static final obxId = obx.QueryIntegerProperty<CachedMessage>(
    _entities[1].properties[0],
  );

  /// See [CachedMessage.id].
  static final id = obx.QueryStringProperty<CachedMessage>(
    _entities[1].properties[1],
  );

  /// See [CachedMessage.conversationId].
  static final conversationId = obx.QueryStringProperty<CachedMessage>(
    _entities[1].properties[2],
  );

  /// See [CachedMessage.senderId].
  static final senderId = obx.QueryStringProperty<CachedMessage>(
    _entities[1].properties[3],
  );

  /// See [CachedMessage.content].
  static final content = obx.QueryStringProperty<CachedMessage>(
    _entities[1].properties[4],
  );

  /// See [CachedMessage.mediaUrl].
  static final mediaUrl = obx.QueryStringProperty<CachedMessage>(
    _entities[1].properties[5],
  );

  /// See [CachedMessage.messageType].
  static final messageType = obx.QueryStringProperty<CachedMessage>(
    _entities[1].properties[6],
  );

  /// See [CachedMessage.isSeen].
  static final isSeen = obx.QueryBooleanProperty<CachedMessage>(
    _entities[1].properties[7],
  );

  /// See [CachedMessage.replyToMessageId].
  static final replyToMessageId = obx.QueryStringProperty<CachedMessage>(
    _entities[1].properties[8],
  );

  /// See [CachedMessage.callId].
  static final callId = obx.QueryStringProperty<CachedMessage>(
    _entities[1].properties[9],
  );

  /// See [CachedMessage.createdAt].
  static final createdAt = obx.QueryStringProperty<CachedMessage>(
    _entities[1].properties[10],
  );

  /// See [CachedMessage.syncedAt].
  static final syncedAt = obx.QueryStringProperty<CachedMessage>(
    _entities[1].properties[11],
  );

  /// See [CachedMessage.replyContent].
  static final replyContent = obx.QueryStringProperty<CachedMessage>(
    _entities[1].properties[12],
  );

  /// See [CachedMessage.replySenderId].
  static final replySenderId = obx.QueryStringProperty<CachedMessage>(
    _entities[1].properties[13],
  );

  /// See [CachedMessage.replyMessageType].
  static final replyMessageType = obx.QueryStringProperty<CachedMessage>(
    _entities[1].properties[14],
  );
}

/// [CachedProfile] entity fields to define ObjectBox queries.
class CachedProfile_ {
  /// See [CachedProfile.obxId].
  static final obxId = obx.QueryIntegerProperty<CachedProfile>(
    _entities[2].properties[0],
  );

  /// See [CachedProfile.id].
  static final id = obx.QueryStringProperty<CachedProfile>(
    _entities[2].properties[1],
  );

  /// See [CachedProfile.username].
  static final username = obx.QueryStringProperty<CachedProfile>(
    _entities[2].properties[2],
  );

  /// See [CachedProfile.fullName].
  static final fullName = obx.QueryStringProperty<CachedProfile>(
    _entities[2].properties[3],
  );

  /// See [CachedProfile.avatarUrl].
  static final avatarUrl = obx.QueryStringProperty<CachedProfile>(
    _entities[2].properties[4],
  );

  /// See [CachedProfile.coverUrl].
  static final coverUrl = obx.QueryStringProperty<CachedProfile>(
    _entities[2].properties[5],
  );

  /// See [CachedProfile.createdAt].
  static final createdAt = obx.QueryStringProperty<CachedProfile>(
    _entities[2].properties[6],
  );

  /// See [CachedProfile.syncedAt].
  static final syncedAt = obx.QueryStringProperty<CachedProfile>(
    _entities[2].properties[7],
  );
}

/// [FailedMessage] entity fields to define ObjectBox queries.
class FailedMessage_ {
  /// See [FailedMessage.obxId].
  static final obxId = obx.QueryIntegerProperty<FailedMessage>(
    _entities[3].properties[0],
  );

  /// See [FailedMessage.localId].
  static final localId = obx.QueryStringProperty<FailedMessage>(
    _entities[3].properties[1],
  );

  /// See [FailedMessage.conversationId].
  static final conversationId = obx.QueryStringProperty<FailedMessage>(
    _entities[3].properties[2],
  );

  /// See [FailedMessage.senderId].
  static final senderId = obx.QueryStringProperty<FailedMessage>(
    _entities[3].properties[3],
  );

  /// See [FailedMessage.content].
  static final content = obx.QueryStringProperty<FailedMessage>(
    _entities[3].properties[4],
  );

  /// See [FailedMessage.messageType].
  static final messageType = obx.QueryStringProperty<FailedMessage>(
    _entities[3].properties[5],
  );

  /// See [FailedMessage.replyToMessageId].
  static final replyToMessageId = obx.QueryStringProperty<FailedMessage>(
    _entities[3].properties[6],
  );

  /// See [FailedMessage.createdAt].
  static final createdAt = obx.QueryStringProperty<FailedMessage>(
    _entities[3].properties[7],
  );

  /// See [FailedMessage.replyContent].
  static final replyContent = obx.QueryStringProperty<FailedMessage>(
    _entities[3].properties[8],
  );

  /// See [FailedMessage.replySenderId].
  static final replySenderId = obx.QueryStringProperty<FailedMessage>(
    _entities[3].properties[9],
  );

  /// See [FailedMessage.mediaUrl].
  static final mediaUrl = obx.QueryStringProperty<FailedMessage>(
    _entities[3].properties[10],
  );
}
